version: "3.9"


services:


  chatbot:


    build: .


    container_name: chatbot_rag


    ports:

      - "5000:5000"



    volumes:

      - .:/app



    environment:

      GOOGLE_API_KEY: TU_API_KEY_GEMINI



    restart: always